### ISSUE TITLE
Using gem with multiple api keys

### ISSUE THREAD

**Issue by soolaimon** [hvssle/onfido#15]
I work on a multitenanted application and we're considering implementing onfido for multiple clients. If each of our clients has an onfido API key, I'm wondering if, rather than setting the API Key in an initializer, I could do something like

```
class OnfidoIntegration
   def initialize
      Onfido.configure do |config|
         ...
      end
   end
```

or would that set the config globally, causing conflicts? Is there a better way to accomplish this? Can I just pass the key in every time I do `Onfido::API.new`?

Thanks!

**Comment by dnlserrano** [comment]
Addressed in https://github.com/hvssle/onfido/pull/17.
