### ISSUE TITLE
how to update address list?

### ISSUE THREAD

**Issue by tompave** [hvssle/onfido#4]
Hi @PericlesTheo, how do I `PATCH` or `PUT` the `applicant` to add more `addresses` later?

**Comment by PericlesTheo** [comment]
As far as I know, once a user resource has been created, you cannot update their info.

**Comment by tompave** [comment]
Waaaaat?

**Comment by PericlesTheo** [comment]
I've discussed this before with Onfido and currently you cannot update or delete an Applicant. Their [API Doc](https://onfido.com/documentation#applicants) doesn't support it.

**Comment by tompave** [comment]
Ok, thanks
