### ISSUE TITLE
API V2

### ISSUE THREAD

**Issue by PericlesTheo** [hvssle/onfido#9]
Hey @greysteil, Onfido seems to have released a second version of the API. From the [changelog](https://onfido.com/documentation#changelog) I don't think there are any breaking changes so there is nothing to do but it might be helpful to mention in the documentation that the gem currently supports V1 & v2.

WDYT?

**Comment by greysteil** [comment]
Good shout. Update the readme in https://github.com/hvssle/onfido/commit/af1e326cbca58fc69f086cb5f30a1c1a12406b72 and will push a new version in a bit.

**Comment by PericlesTheo** [comment]
Nice one
